### ISSUE TITLE
simpleRowTemplate not found in Firefox

### ISSUE THREAD

**Issue by optikalefx** [stevenrskelton/sortable-table#26]
This code works perfectly in Chrome. In Firefox this

http://cl.ly/image/041816280x17  
gives me an alert that simpleRowTemplate is not found. This only happens in Firefox. Your example works fine, I can't figure out why this is throwing that error here.  The only thing of note is that this is HTML that is build and then rendered on the page. Again works fine in Chrome.  When I debug the JS for this line 428 `var t = this.querySelector('#'+templateId);` gives a `null` value.  Not sure why, that element does exist. My guess is some kind of timing issue? But I'm not sure how to change that.

Thanks!

    <sortable-table class="bootstrap" rowtemplate="simpleRowTemplate">
		<sortable-column>Class Name</sortable-column>
		<sortable-column># of {?isTeacher}students{:else}employees{/isTeacher}</sortable-column>
		<sortable-column>Link</sortable-column>
		<sortable-column>Archive</sortable-column>
		<template id="simpleRowTemplate">
			<td>{~lb}{~lb}record.row.name{~rb}{~rb}</td>
	    		<td>{~lb}{~lb}record.row.students.length{~rb}{~rb}</td>
			<td>
				<input type="text" class="input large customUrl"
						value="{~lb}{~lb}record.row.url{~rb}{~rb}"
					/>
				<button class="btn btn-success copyUrl"
						data-clipboard-text="{~lb}{~lb}record.row.url{~rb}{~rb}"
					>Copy</button>
			</td>
			<td class="align-right">
				<button class="btn btn-info archive">Archive</button>
			</td>
		</template>
	</sortable-table>

**Comment by optikalefx** [comment]
More notes, running a querySelectorAll("*"); in chrome shows all the inner parts, in FF it shows length 0, none.

http://cl.ly/image/2U2Z2H2M0203

**Comment by optikalefx** [comment]
Note that however, this.innerHTML does show the correct HTML with the template for both FF and chrome

http://cl.ly/image/0I2v2H2J0M07

So it seems that HTML is just not getting parsed as DOM

**Comment by optikalefx** [comment]
For the purpose of testing, I made the table template really simple, same results with FF.

http://cl.ly/image/0V112E1L0A2V
http://cl.ly/image/3D132s1K112f

**Comment by optikalefx** [comment]
This is so weird.

With a debugger statement in, i have access to `this`.

    // no results
    this.querySelectorAll("*");

    // 1 result http://cl.ly/image/2P1i2p1g2418
    this.querySelector("template");

    // id is simpleRowTemplate http://cl.ly/image/2C271m1K120O
    this.querySelector("template").id;

    // null
    this.querySelector("#simpleRowTemplate");


WTF

**Comment by optikalefx** [comment]
with a hot fix applied to move on, `if(!t) t = this.querySelector("template");`  no errors, but it doesn't populate the rows with any data. Or headers for that matter

**Comment by stevenrskelton** [comment]
Commit https://github.com/stevenrskelton/sortable-table/commit/8821760803408b643863726fe481017d2557a045 fixes this issue.

`this.querySelector` seems to be empty, but the templates are in `this.children`; so it's a matter of manually iterating over them to find stuff.
