### ISSUE TITLE
Element not compatible with Vulcanize

### ISSUE THREAD

**Issue by LM450N** [stevenrskelton/sortable-table#30]
Hello,

I use Grunt for build my app and I deploy on Google App Engine.
Locally the table works like a charm and I'm pretty impressed.
On App Engine no data is rendered but I can see them with the elements explorer.

Grunt uses the Vulcanize module to concatenate the HTML.
When I deploy the app not "vulcanized" the element is working but it's less powerful.
This problem happens only with the table.
The "vulcanisation" does not affect the Polymer elements (for example).

Do you use another module for minify your app before deploy ?
It's pretty weird, do you have an idea why this component isn't compatible with the Vulcanize module ?

(NB: sorry for my poor english).

![sort-table-not-rendering-on-app-engine](https://cloud.githubusercontent.com/assets/2325091/5791199/c511f730-9ec2-11e4-8859-0543451f1a9a.png)

**Comment by stevenrskelton** [comment]
Vulcanize works for me, I'm not sure why yours is broken.

Are there any failed network requests?
Any JavaScript warnings or errors in the console?
Do other pages with web components work?
Are all pages with a `sortable-table` broken?

**Comment by LM450N** [comment]
Hello,

I have not network requests failed.
No error / warning JavaScript in the console.

My app has a `core-toolbar`, `paper-tabs` and `animated-pages`, that's all.
The `sortable-table` is into the first page and the two others are empties.

I've already used your component in another project and the tables was never rendered after vulcanization.
This other project has some paper-buttons on the same page and they work fine.
My app was generated with Yeoman.
In my Gruntfile I have to comment "vulcanize" and "usemin" to render the table (but the app is not minified).

![gruntfile_configuration_lm450n](https://cloud.githubusercontent.com/assets/2325091/5793680/14bd3ef4-9f4d-11e4-8b45-6c5145f217f8.png)

I'll try to insert another component into the same page when I'll have more time (tomorrow I think) and I'll keep you in touch.

Thank you for your help !

**Comment by LM450N** [comment]
Hi Steven,

As you can see (on the attachment) I tried with a `google-chart` component before and after the `sortable-table`.
I added a title to see the table location.

Locally everything works fine but after the build, the `sortable-table` is broken.
We can also see it's "only" the data part who does not work.
The data are provided by the hard way, like in the example.

Can you show me your settings options for the Vulcanize and Usemin task in your Gruntfile please ?
I suspect a misconfiguration. Something like a quote interpretation.

Again, sorry for my poor english.

![table_not_rendered_after_vulcanize](https://cloud.githubusercontent.com/assets/2325091/5800567/78df3976-9fe0-11e4-91c3-9f27fbf80f81.png)

**Comment by stevenrskelton** [comment]
I'm not currently using Grunt, but now is the perfect time for me to start!

I'm going to setup Grunt from scratch using the same modules as you, and I'll let you know if it works.

**Comment by LM450N** [comment]
Look at the [Yeoman](http://yeoman.io/) tool ;).

I installed Yeoman and the [generator-polymer](https://github.com/yeoman/generator-polymer) with NPM.
I created the app with the `yo polymer:app` command.

A Gruntfile is initialized and I have not modified this file except the sourcemap  argument for SASS I turned it to `false` because Grunt was not able to start.

**Comment by LM450N** [comment]
Hi !

Is it normal not see the tables on the [sortable-table examples](http://files.stevenskelton.ca/sortable-table/examples/themes/bootstrap.html) page ?

Actually, I have exactly the same issue after using Vulcanize on my app.

**Comment by stevenrskelton** [comment]
I'm intentionally hiding the data rows on the [/themes/bootstrap.html](http://files.stevenskelton.ca/sortable-table/examples/themes/bootstrap.html) page

**Comment by LM450N** [comment]
I'm sorry, maybe I made a mistake. It's not the _Vulcanization_ who breaks the build but the _usemin_ __Grunt__ task. This corresponds to the code's minification. It's pretty difficult to find the cause because for this, I have to search a parse mistake into the minified code. I think it's due by a quote mark in a comment of the component or something like that.

What tool of minification you're using ?

When I'll have more time, I'll try to build a project with another tool instead of __Grunt__, maybe __Brunch__ (or __Gulp__).

**Comment by stevenrskelton** [comment]
I'm not using any minimizer at the moment; only LAN and non-production setups so far.

I can confirm that I'm seeing the same issues with usemin, not really in a position to spend any time debugging it :see_no_evil: , I'm hoping newer versions of Polymer will fix it.

**Comment by wintersandroid** [comment]
I dont have any problem using the "build" task of yeoman polymer with the sortable table. I have two web apps that currently are vulcanized with no issue.. One quite extensively styles the table as well.

**Comment by stevenrskelton** [comment]
@wintersandroid :metal:

**Comment by LM450N** [comment]
@wintersandroid :
Does the build task runs a "usemin" operation ?
Which builder you're using ? Grunt, Gulp, Brunch maybe something else ?

@stevenrskelton :
Have you seen Polymer 0.8 (and the next versions) will [not be compatible][1] with the `polymer-elements` of the version 0.5.x ? Your element is it ?

I'll be back...with some answers...I hope... :smile: 

[1]: https://divshot.com/blog/web-components/polymer-0-8-sneak-peek/

**Comment by LM450N** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by d4nyll** [comment]
Not sure if this is related, but I am getting the following error:

```
error:   Promise rejection: Error: This version of vulcanize is not compatible with Polymer < 0.8. Please use vulcanize 0.7.x. File:
bower_components/sortable-table/sortable-table.html
error:   Error: This version of vulcanize is not compatible with Polymer < 0.8. Please use vulcanize 0.7.x. File: bower_components/so
rtable-table/sortable-table.html
    at Vulcan.flatten (/home/administrator/.nvm/versions/node/v7.4.0/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.j
s:237:13)
    at Vulcan.flatten (/home/administrator/.nvm/versions/node/v7.4.0/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.j
s:283:30)
    at Vulcan.flatten (/home/administrator/.nvm/versions/node/v7.4.0/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.j
s:283:30)
    at Vulcan.<anonymous> (/home/administrator/.nvm/versions/node/v7.4.0/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulc
an.js:466:26)
```

I'm using Polymer `^1.5.0` and `sortable-table` `^0.11.1`
