### ISSUE TITLE
Binding to results from core-ajax

### ISSUE THREAD

**Issue by fils** [stevenrskelton/sortable-table#31]
I hacked together the following and it works with a simple template repeat.  However, I thought it would be nice to use the advanced features or sortable tables.  I am not sure how to bind the results of the core-ajax call to the sortable tables though.  (I also put it at http://jsbin.com/bejudo/1/edit?html )

I included the whole html but the only parts of concern are the sortable-table vs template repeat lines 2/3rds down.

Thanks
Doug

```html
<link rel="import" href="./bower_components/polymer/polymer.html">
<link rel="import" href="./bower_components/paper-input/paper-input.html">
<link rel="import" href="./bower_components/paper-button/paper-button.html">
<link rel="import" href="./bower_components/core-ajax/core-ajax.html">
<link rel="import" href="./bower_components/sortable-table/sortable-table.html">
<polymer-element name="add-node" attributes="url">
  <template>
    <style>
      paper-input {
        color:#000000;
        text-align:left;
      }
      paper-button.colored {
        background:#000000;
        color:#ffffff;
      }
      .centered {
        display:block;
        text-align:center;
        width:100%;
      }
    </style>
    
    <form id="form_1">
      <paper-input floatingLabel label="Leg" value="{{leg}}"></paper-input>
       <paper-input floatingLabel label="Site:" value="{{site}}"></paper-input>
       <paper-input floatingLabel label="Hole:" value="{{hole}}"></paper-input>
       <paper-input floatingLabel label="Genus:" value="{{genus}}"></paper-input>
       <paper-input floatingLabel label="Species:" value="{{species}}"></paper-input>
       <paper-input floatingLabel label="Sub-species:" value="{{subspecies}}"></paper-input>
       <paper-input floatingLabel label="Fossile Group:" value="{{fossile_group}}"></paper-input>
       <paper-input floatingLabel label="Time Range:" value="{{time_range}}"></paper-input>
       <paper-input floatingLabel label="Latitude:" value="{{latitude}}"></paper-input>
       <paper-input floatingLabel label="Longitude:" value="{{longitude}}"></paper-input>
       <paper-input floatingLabel label="Ocean:" value="{{ocean}}"></paper-input>
       <paper-input floatingLabel label="Hole ID:" value="{{hole_id}}"></paper-input>
      <div class="centered">
        <paper-button on-tap="{{doSend}}" class="colored"  label="Search"></paper-button>
      </div>
    </form>

    <core-ajax id="ajax"  method="GET" handleAs="json" url="{{url}}" response="{{response}}" >
    </core-ajax>

<sortable-table columns='["Leg","Site","Hole","Hole_id", "Ocean_code", "Taxon_abundance", "Taxon",
"Fossil_group", "Water_depth", Sample_age_ma", "Sample_depth_mbsf", "Latitude", "Longitude"]'>
{{response}}
    </sortable-table>
<!-- 
    <template repeat="{{response}}"><p>{{Leg}} {{Site}} {{Hole}} {{Taxon}} {{Sample_age_ma}} {{Latitude}} {{Longitude}} </p></template> -->
  </template>
  <script>
    Polymer('add-node', {
      doSend: function(event, detail, sender){
         this.$.ajax.go();
      }
    });
  </script>
</polymer-element>
```

**Comment by stevenrskelton** [comment]
Putting a `{{response}}` as a #text element won't work, I believe that it will serialize the JSON as `[object],[object],...,[object]`.

Instead, use 
`<sortable-table data="{{response}}"></sortable-table>`

You might run into issue defining `columns` as an array like that.  If you do, use `<sortable-column>` tags; they are better supported. (You should be able to use an array, the 2 should be equivalent, but I needed to fix a bug)

**Comment by fils** [comment]
Thanks..  I tried it ..   putting the data= attribute in and using the sortable-column in as I saw in the documentation.

I am getting an error, but I don't know if it's on my end (the JSON does validate).   In case they were useful I include them below.  

Thanks for the help..  this looks like a great component.


"Exception caught during observer callback: .pageSizeChanged@http://127.0.0.1:1718/bower_components/sortable-table/sortable-table.html.js:279:9
.dataChanged@http://127.0.0.1:1718/bower_components/sortable-table/sortable-table.html.js:271:51
g.invokeMethod@http://127.0.0.1:1718/bower_components/polymer/polymer.js:14:2498
g.notifyPropertyChanges@http://127.0.0.1:1718/bower_components/polymer/polymer.js:14:2392
x.prototype.report_@http://127.0.0.1:1718/bower_components/polymer/polymer.js:12:21063
D.prototype<.check_@http://127.0.0.1:1718/bower_components/polymer/polymer.js:12:25411
a.Platform.performMicrotaskCheckpoint@http://127.0.0.1:1718/bower_components/polymer/polymer.js:12:21527
b/<@http://127.0.0.1:1718/bower_components/polymer/polymer.js:13:23051
c@http://127.0.0.1:1718/bower_components/polymer/polymer.js:13:22776
notifyObservers@http://127.0.0.1:1718/bower_components/webcomponentsjs/webcomponents.js:577:13
handle@http://127.0.0.1:1718/bower_components/webcomponentsjs/webcomponents.js:522:1
" polymer.js:12:21140

"Exception caught during observer callback: .sortByKey@http://127.0.0.1:1718/bower_components/sortable-table/sortable-table.html.js:388:9
g.prototype.transform@http://127.0.0.1:1718/bower_components/polymer/polymer.js:12:3659
l.prototype.getValue@http://127.0.0.1:1718/bower_components/polymer/polymer.js:12:6588
d@http://127.0.0.1:1718/bower_components/polymer/polymer.js:12:6235
F.prototype.observedCallback_@http://127.0.0.1:1718/bower_components/polymer/polymer.js:12:25666
x.prototype.report_@http://127.0.0.1:1718/bower_components/polymer/polymer.js:12:21063
D.prototype<.check_@http://127.0.0.1:1718/bower_components/polymer/polymer.js:12:25411
a.Platform.performMicrotaskCheckpoint@http://127.0.0.1:1718/bower_components/polymer/polymer.js:12:21527
b/<@http://127.0.0.1:1718/bower_components/polymer/polymer.js:13:23051
c@http://127.0.0.1:1718/bower_components/polymer/polymer.js:13:22776
notifyObservers@http://127.0.0.1:1718/bower_components/webcomponentsjs/webcomponents.js:577:13
handle@http://127.0.0.1:1718/bower_components/webcomponentsjs/webcomponents.js:522:1
" polymer.js:12:21140

**Comment by stevenrskelton** [comment]
Those are due to `core-ajax` setting the `data` value to `null` while it loads.  I push a fix for that but I haven't fully tested it yet.
