### ISSUE TITLE
tests?

### ISSUE THREAD

**Issue by tirams** [stevenrskelton/sortable-table#41]
are there unit tests for this? or plans for tests

**Comment by stevenrskelton** [comment]
:+1: No tests yet, but I have started working on them.  They are my first priority, I'd love to get them in to help migrate to Polymer 0.8.

Tests are going to be using Polymer's https://github.com/Polymer/web-component-tester, which bundles http://mochajs.org/ and http://chaijs.com/ , and has extra stuff useful for web components.

My plan was to inline tests into the example documentation pages (which up until now served as manual tests), the hold-up has been trying to do it without duplicating everything.
