### ISSUE TITLE
Smarter Sorting

### ISSUE THREAD

**Issue by SebastianBoyd** [stevenrskelton/sortable-table#42]
The sort should be able to recognize different data types such as date times like what excel does when you import a data set.

**Comment by stevenrskelton** [comment]
I added the ability to specify the `datatype` for columns, giving more accurate sorting.
I'll see if I can also make the default sorting better at type inference.

**Comment by LM450N** [comment]
+1

Louchart Mason
Google+ <https://plus.google.com/+MasonLouchart/posts> | LM+
<https://plus.google.com/+Louchart-masonFr/posts> | louchart-mason.fr |
Twitter <http://twitter.com/louchart_mason> | Youtube
<https://www.youtube.com/user/LouchartMason> | GitHub
<https://github.com/LM450N>

2015-04-27 4:30 GMT+02:00 Steven Skelton <notifications@github.com>:
